# copied from https://github.com/sys-bio/libantimonyjs/blob/develop/.github/workflows/build-libantimonyjs-github-actions.yml

name: build-libsbmlsim
run-name: Build LibSBMLSim
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
      
      - name: Build everything 🤞
        run: ./build.sh

      - name: Create release directory
        run: mkdir release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libsbmlsim.js
          asset_name: libsbmlsim.js
          tag: ${{ github.ref }}
          overwrite: true
